// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.7.0.0
//      SpecFlow Generator Version:1.7.0.0
//      Runtime Version:4.0.30319.235
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace ProtoTimeSpecs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.7.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("In order to format dates in a more programmer-friendly way\r\nthe FormatLike\r\nforma" +
        "ts a date given a human-readable example.")]
    public partial class StampingADateFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ProtoTimeSpecs.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Stamping a date", "In order to format dates in a more programmer-friendly way\r\nthe FormatLike\r\nforma" +
                    "ts a date given a human-readable example.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Formatting dates by example")]
        [NUnit.Framework.CategoryAttribute("date")]
        [NUnit.Framework.TestCaseAttribute("January", "September", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Jan", "Sep", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Jan 1", "Sep  8", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Jan 31", "Sep 08", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Jan 31", "Sep 08", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Jan 1, 1999", "Sep  8, 2011", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Monday", "Thursday", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Tue, Jan 1", "Thu, Sep  8", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Tuesday, January 1, 1999", "Thursday, September  8, 2011", new string[0])]
        [NUnit.Framework.TestCaseAttribute("31/1999", "09/2011", new string[0])]
        [NUnit.Framework.TestCaseAttribute("01/31", "09/08", new string[0])]
        [NUnit.Framework.TestCaseAttribute("01/99", "09/11", new string[0])]
        [NUnit.Framework.TestCaseAttribute("01/31/1999", "09/08/2011", new string[0])]
        [NUnit.Framework.TestCaseAttribute("12/31/99", "09/08/11", new string[0])]
        [NUnit.Framework.TestCaseAttribute("31/12", "08/09", new string[0])]
        [NUnit.Framework.TestCaseAttribute("31/12/99", "08/09/11", new string[0])]
        [NUnit.Framework.TestCaseAttribute("31-Jan-1999", "08-Sep-2011", new string[0])]
        [NUnit.Framework.TestCaseAttribute("1999-12-31", "2011-09-08", new string[0])]
        [NUnit.Framework.TestCaseAttribute("DOB: 12-31-1999", "DOB: 09-08-2011", new string[0])]
        public virtual void FormattingDatesByExample(string example, string output, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "date"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Formatting dates by example", @__tags);
#line 7
  this.ScenarioSetup(scenarioInfo);
#line 8
    testRunner.Given("the date September 8, 2011");
#line 9
    testRunner.When(string.Format("I stamp the example \"{0}\"", example));
#line 10
    testRunner.Then(string.Format("I produce \"{0}\"", output));
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#endregion
